services:
  backend:
    build: ./Backend
    container_name: ci-cd-backend
    volumes:
      - ./Backend:/app
    ports:
      - '3000:3000'
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    restart: on-failure

  mongodb:
    image: mongo
    container_name: ci-cd-mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    restart: always
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
